/*
    割り込みハンドラ関数
    void* Frame - 割り込みフレーム
    (u64 ErrorCode) エラーコード
    作成日 2025-05-30
*/

#pragma once

#include "basetype.h"

typedef struct interrupt_frame
{
    u64 Rip;
    u64 Cs;
    u64 Rflags;
    u64 Rsp;
    u64 Ss;
} interrupt_frame_t;

__attribute__((interrupt)) void DefaultHandler(interrupt_frame_t *);
__attribute__((interrupt)) void IsrDivideError(void*);
__attribute__((interrupt)) void IsrInvalidOpcode(void*);
__attribute__((interrupt)) void IsrDoubleFault(void*, u64);
__attribute__((interrupt)) void IsrGPF(void*, u64);
__attribute__((interrupt)) void IsrPageFault(void*, u64);
__attribute__((naked)) void IsrKeyboard(void);
__attribute__((naked)) void IsrMouse(void);
__attribute__((naked)) void IsrTimer(void);

void Handler(interrupt_frame_t *, u64);

__attribute__((interrupt)) void Handler0(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler1(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler2(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler3(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler4(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler5(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler6(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler7(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler8(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler9(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler10(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler11(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler12(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler13(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler14(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler15(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler16(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler17(struct interrupt_frame* frame, u64);
__attribute__((interrupt)) void Handler18(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler19(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler20(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler21(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler22(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler23(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler24(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler25(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler26(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler27(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler28(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler29(struct interrupt_frame* frame);
__attribute__((interrupt)) void Handler30(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler31(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler32(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler33(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler34(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler35(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler36(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler37(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler38(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler39(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler40(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler41(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler42(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler43(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler44(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler45(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler46(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler47(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler48(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler49(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler50(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler51(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler52(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler53(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler54(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler55(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler56(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler57(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler58(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler59(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler60(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler61(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler62(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler63(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler64(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler65(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler66(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler67(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler68(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler69(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler70(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler71(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler72(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler73(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler74(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler75(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler76(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler77(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler78(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler79(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler80(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler81(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler82(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler83(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler84(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler85(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler86(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler87(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler88(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler89(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler90(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler91(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler92(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler93(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler94(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler95(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler96(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler97(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler98(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler99(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler100(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler101(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler102(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler103(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler104(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler105(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler106(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler107(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler108(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler109(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler110(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler111(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler112(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler113(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler114(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler115(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler116(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler117(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler118(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler119(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler120(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler121(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler122(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler123(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler124(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler125(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler126(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler127(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler128(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler129(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler130(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler131(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler132(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler133(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler134(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler135(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler136(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler137(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler138(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler139(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler140(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler141(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler142(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler143(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler144(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler145(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler146(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler147(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler148(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler149(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler150(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler151(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler152(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler153(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler154(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler155(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler156(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler157(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler158(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler159(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler160(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler161(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler162(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler163(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler164(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler165(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler166(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler167(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler168(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler169(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler170(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler171(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler172(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler173(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler174(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler175(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler176(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler177(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler178(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler179(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler180(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler181(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler182(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler183(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler184(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler185(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler186(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler187(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler188(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler189(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler190(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler191(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler192(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler193(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler194(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler195(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler196(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler197(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler198(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler199(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler200(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler201(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler202(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler203(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler204(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler205(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler206(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler207(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler208(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler209(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler210(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler211(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler212(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler213(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler214(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler215(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler216(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler217(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler218(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler219(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler220(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler221(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler222(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler223(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler224(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler225(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler226(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler227(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler228(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler229(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler230(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler231(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler232(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler233(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler234(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler235(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler236(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler237(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler238(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler239(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler240(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler241(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler242(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler243(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler244(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler245(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler246(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler247(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler248(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler249(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler250(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler251(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler252(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler253(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler254(struct interrupt_frame *frame);
__attribute__((interrupt)) void Handler255(struct interrupt_frame *frame);

__attribute__((interrupt)) void IsrIRQ7(void*);